In [6]:
import numpy as np

# Create a 1D array
arr_1d = np.arange(12)
print("Original 1D array:", arr_1d)
print("Shape of 1D array:", arr_1d.shape)

# Reshape to a 2D array (3 rows, 4 columns)
arr_2d = arr_1d.reshape(3, 4)
print("\nReshaped 2D array:\n", arr_2d)
print("Shape of 2D array:", arr_2d.shape)

# Reshape to a 3D array (2 "layers", 2 rows, 3 columns)
arr_3d = arr_1d.reshape(2, 2, 3)
print("\nReshaped 3D array:\n", arr_3d)
print("Shape of 3D array:", arr_3d.shape)

# Reshape with an inferred dimension
arr_inferred = arr_1d.reshape(4, -1)
print("\nReshaped array with inferred dimension:\n", arr_inferred)
print("Shape of array with inferred dimension:", arr_inferred.shape)

Original 1D array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape of 1D array: (12,)

Reshaped 2D array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape of 2D array: (3, 4)

Reshaped 3D array:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Shape of 3D array: (2, 2, 3)

Reshaped array with inferred dimension:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Shape of array with inferred dimension: (4, 3)


In [34]:
import numpy as np 
my_array = np.arange(1,10) 

my_array = my_array.reshape(3,3)
print("MY ARRAY:",my_array)

my_array_sum = my_array.sum(0)
print("Columns sum:",my_array_sum)

my_array_sum = my_array.sum(-1)
print("Rows sum:",my_array_sum)

my_array_sum = my_array.sum(axis=1)
print("Rows:",my_array_sum)

arr_prod = my_array.prod()
print("dot product:",arr_prod)

arr_average = my_array.mean()
print(" mean:",arr_average)

array_max,array_min = my_array.max(),my_array.min()
print(array_max, array_min)
print("Index of min and max:",array_max.argmax(), array_min.argmin())

peak_to_peak = np.ptp(my_array)
print(peak_to_peak)

#flatterning
array_flat = my_array.reshape(my_array.size)
print(array_flat)

array_flat = my_array.flatten()
array_flat = my_array.ravel()
print("my_array is referenced by ravel himself:", array_flat)

MY ARRAY: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Columns sum: [12 15 18]
Rows sum: [ 6 15 24]
Rows: [ 6 15 24]
dot product: 362880
 mean: 5.0
9 1
Index of min and max: 0 0
8
[1 2 3 4 5 6 7 8 9]
my_array is referenced by ravel himself: [1 2 3 4 5 6 7 8 9]
